name: Sync and merge upstream repository with your current repository
description: Syncs and merges your current repository with the upstream repository. Fork of https://github.com/mheene/sync-upstream-repo.
author: Dabreadman

inputs:
  upstream_repo:
    description: URL of gitHub public upstream repo
    required: true
  branch:
    description: Branch main of merge branch
    required: false
    default: "main"
  token:
    description: GitHub Bot token
    required: true
  merge_args:
    description: Git merge arguments
    required: false
    default: ""
  push_args:
    description: Git push arguments
    required: false
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.upstream_repo }}
    - ${{ inputs.branch }}
    - ${{ inputs.token }}
    - ${{ inputs.merge_args }}
    - ${{ inputs.push_args }}

branding:
  icon: "git-merge"
  color: "blue"
