name: Sync and merge upstream repository with your current repository
description: Syncs and merges your current repository with the upstream repository. Fork of https://github.com/mheene/sync-upstream-repo.
author: Dabreadman

inputs:
  upstream_repo:
    description: URL of gitHub public upstream repo
    required: true
  branch:
    description: Branch main of merge branch
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.upstream_repo }}
    - ${{ inputs.branch }}

branding:
  icon: "git-merge"
  color: "blue"
